import streamlit as st
st.title("User Login Form")
uid=st.text_input("User Id:-")
pswd=st.text_input("Password",type="password")
agree = st.checkbox("I Agree") 
gender = st.radio("Gender",["Male","Female"]) 
skills = st.multiselect("Skills",["Python","Java"])
course = st.selectbox("Course",["Python","AI"]) 
age = st.slider("Age",0,100) 
age = st.number_input("Age") 
msg = st.text_area("Feedback")
name = st.text_input("Name") 

st.divider()
st.button("Login")
st.button("Reset")